### ISSUE TITLE
Fetching "master" branch --> "main" branch 

### ISSUE THREAD

**Issue by glee2429** [tomasbjerre/git-changelog-lib#100]
Hi, thanks for sharing a great open-sourced project! 

While integrating the plugin to a codebase, I noticed an issue about fetching the "master" branch as Github is moving toward the direction of replacing "master" with "main" (https://github.com/github/renaming). 

Initially, I got the error message below when there is only "main," but I managed to fixed this by creating a "master" branch. I believe this problem can be easily fixed by fetching "main" instead of "master." 

	  GitChangelog
          se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException: master not found in:
          Repo: Repository[/Users/clairel/Kiva/checkout-orchestrator/.git]
          HEAD
          refs/heads/CLP-107-ratelimit
          refs/heads/SemVerPlugin
          refs/heads/main
          refs/remotes/origin/CLP-104-mdc-explore
          refs/remotes/origin/CLP-111
          refs/remotes/origin/HEAD
          refs/remotes/origin/failing-test
          refs/remotes/origin/hack
          refs/remotes/origin/main
          refs/tags/v0.1.0
          refs/tags/v1.0.0
          refs/tags/v1.0.1
          refs/tags/v1.0.2
          refs/tags/v1.1.0
          refs/tags/v1.2.0
          refs/tags/v1.3.0
          refs/tags/v1.4.0

Relevant links:
#28  
https://github.com/tomasbjerre/git-changelog-lib/commit/dd4633ba627695db650fc3130825bdf4feacba2b

**Comment by tomasbjerre** [comment]
The branches to compare is configurable. Master is just default value.

**Comment by glee2429** [comment]
Got it. Can you point me where in which file to change for updating the configuration?

**Comment by tomasbjerre** [comment]
It depends on how you use this library. What tool/plugin do you use?

**Comment by glee2429** [comment]
I'm using `git-changelog-gradle-plugin` for a Kotlin project; I guess I can specify the configuration when defining a task? Here's what I got so far: 

      tasks.create<se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask>("gitChangelogTask") {
          file = File("CHANGELOG.md")
          fromRepo = File("$projectDir").toString()
          // settingsFile = rootProject.file("CHANGELOG.md").absolutePath
          templateContent = """
        // Template here!
       """
      }
Also, another quick question: I don't necessarily need to use `settingsFile = rootProject.file("CHANGELOG.md").absolutePath` since it's redundant to the previous two lines, right? Thanks for the prompt response!

**Comment by tomasbjerre** [comment]
See fromRef and toRef as used here:

https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/git-changelog-gradle-plugin-example/build.gradle

**Comment by glee2429** [comment]
Updated the task based on the example as follows:

      tasks.create<se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask>("gitChangelogTask") {
          file = File("CHANGELOG.md")
          fromRepo = File("$projectDir").toString()
          fromRef = "v1.0.0"
          toRef = "v1.1.0"
          // settingsFile = rootProject.file("CHANGELOG.md").absolutePath
          templateContent = """
      # Releasenotes in 1.1
      Releasenotes.
      {{#issues}}
       {{#hasLink}}
      ## {{name}} [{{issue}}]({{link}}) {{title}}
       {{/hasLink}}
       {{^hasLink}}
      ## {{name}}
       {{/hasLink}}
       {{#commits}}
        {{{hash}}}
      
       {{/commits}}
      {{/issues}}
       """
      }

Then I got this issue: 

      #26
      se.bjurr.gitchangelog.api.exceptions.GitChangelogIntegrationException: Request:Request{method=GET, url=https://api.github.com/repos/kiva/checkout-orchestrator/issues?state=all&per_page=100&page=1, tag=null}
      Error:
      {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/issues#list-repository-issues"}

Do you have any pointer on how to fix this?

**Comment by tomasbjerre** [comment]
Perhaps you repo is not public. And you need authentication:
https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/git-changelog-gradle-plugin-example/build.gradle#L112

Or, remove title from the template so that it does not need the integration.

**Comment by glee2429** [comment]
Fixed it by setting `toRef = "main"`

I created a [PR](https://github.com/tomasbjerre/git-changelog-gradle-plugin/pull/27/files) based on this, so please take a look. Have a nice weekend!
