### ISSUE TITLE
appending the changelog to the previous instead of overwriting

### ISSUE THREAD

**Issue by saharHsn** [tomasbjerre/git-changelog-lib#105]
Hi,
I'm looking for a feature in git-changelog-lib in order to be able to append to the current changelog file, instead of overwriting. Is there any option in this plugin?
Thanks in advanced for your help

**Comment by tomasbjerre** [comment]
No such feature in this library.

If using Jenkins this may help:
https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/106

**Comment by tomasbjerre** [comment]
There is a feature to prepend to file now:
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/api/GitChangelogApi.java#L164
