### ISSUE TITLE
Support JIRA Personal Access Token via Bearer authorization

### ISSUE THREAD

**Issue by rimuln** [tomasbjerre/git-changelog-lib#111]
Actual state:
Jira integration supports usage of basicAuthString that is transformed to Request Header:
Authorization: Basic <token>

Settings allows setting of jiraUserName, jiraPassword and jiraToken properties.

When caller set only jiraToken it isnt clear what this token should be and could be confusing that Personal Access Token generated from Jira didn't works. Because it expect not PAT but Base64 of username:password

Expected state: 
When settings contains only jiraToken it is expected that it is Personal Access Token and then should be set request header to this value:
Authorization: Bearer <token>

Running environment is self hosted Jira in company version 8.20

**Comment by rimuln** [comment]
PR #112 created. It is just quickfix proposal and more nicer solution could be implemented. e.g. some settings/switchers etc

**Comment by tomasbjerre** [comment]
Releasing the library now 1.161.0
