### ISSUE TITLE
Such v1.1.1.0328.00 tags are not supported 

### ISSUE THREAD

**Issue by JL-Code** [tomasbjerre/git-changelog-lib#118]
isReleaseTag Sourcecode：
```java
  public static boolean isReleaseTag(final Tag tag) {
    // v1.1.1.0328.00
    return Pattern.matches("^[0-9]+\\.[0-9]+\\.[0-9]+", tag.getName().replaceAll("[^0-9\\.]", ""));
  }
```
matches is fixed as `^[0-9]+\\.[0-9]+\\.[0-9]+` does not support version 1.1.1.0328.00 and lib does not provide custom `^[0-9]+\\. [0-9]+\\. [0-9]+` entry.
Expectation.
Support v1.1.1.0328.00 version, preferably with customizable isReleaseTag matching rules.

**Comment by tomasbjerre** [comment]
Correct, it supports only semantic versioning.

I dont know how your strategy works.
