### ISSUE TITLE
Dynamic Augmentation of Mustache Context

### ISSUE THREAD

**Issue by kyledmoore** [tomasbjerre/git-changelog-lib#12]
This is more of a feature request than an issue.  I think it would be swell if the user could provide a hunk of JSON that could be added somewhere in the mustache context for later use in the template.  This would allow for user lambdas for dynamic filtering and other general extension when creating the change logs.

For example, using the command line interface, one might:
`git-changelog-lib --repo "\my\repo" --from-commit cec9173674a57866f87506e87cfb1e49a435f2c3 --to-ref HEAD --user-context-file context.json --output-file test.txt`

With context.json having:
`{ foo: 'bar'}`

And a mustache template referencing it:

`
{{#usercontext}}{{!This would be an implicit object where the contents of the user context would be placed by git-changelog-lib}}
We have foo {{foo}}!
{{/usercontext}}
`

Additionally, one-off variables could be passed in rather than having to require a separate file be provided:

`git-changelog-lib --repo "\my\repo" --from-commit cec9173674a57866f87506e87cfb1e49a435f2c3 --to-ref HEAD --user-context-foo bar --output-file test.txt`

My particular use case is wanting to include some information from my build in the change logs, specifically the release number, but it seems this could be useful for other purposes as well.

Thanks for any consideration.

**Comment by tomasbjerre** [comment]
The library has [withExtendedVariables](https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/api/GitChangelogApi.java#L277). I needed it for the [Bitbucket plugin](https://github.com/tomasbjerre/git-changelog-bitbucket-plugin/blob/master/src/main/java/se/bjurr/changelog/bitbucket/application/ChangelogLibService.java#L58). But this can definitely be added to the command line also!

**Comment by tomasbjerre** [comment]
I just released this in 1.3 of [the command line tool](https://github.com/tomasbjerre/git-changelog-command-line
).

`-ex "{\"var1\":\"value1\"}"`

Should be in Maven Central within the hour. Open issue again if any problems.

**Comment by kyledmoore** [comment]
That's great, thanks!
