### ISSUE TITLE
If not configure any server (Jira, Github, Gitlab or Redmi) CHANGELOG file shows Jira and Rermi issues

### ISSUE THREAD

**Issue by clockworkorange** [tomasbjerre/git-changelog-lib#123]
In [IssuesUtil](https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/settings/IssuesUtil.java) class the ifs:
- [if (!isNullOrEmpty(this.settings.getJiraIssuePattern())) {](https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/settings/IssuesUtil.java#L47)
- [if (!isNullOrEmpty(this.settings.getRedmineIssuePattern())) {](https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/settings/IssuesUtil.java#L69)
Never are `null`, and chagelog shows Jira and Redmi issues.

If configure Jira server also shows Redmi issues.

**Comment by tomasbjerre** [comment]
Same as: https://github.com/jenkinsci/git-changelog-plugin/issues/65

**Comment by tomasbjerre** [comment]
Released it in the tools now. Open issue again if not working.
