### ISSUE TITLE
{{ownerName}} is not working correct if a project in subgroup

### ISSUE THREAD

**Issue by wanghu001** [tomasbjerre/git-changelog-lib#128]
We have a project in gitlab, the repo is like: git@gitlab.com:aaaaa/bbbbb/testchangelog.git

After parsed and rendered in template, the {{ownerName}} is only resolved to bbbbb. I think the logic in GitRepoData.repoUrlPartFromEnd needs adjustment. 

Thank you!

**Comment by tomasbjerre** [comment]
Would you want aaaaa to be the owner here?

**Comment by wanghu001** [comment]
the ownerName should be containing aaaaa/bbbbb in order for the url to repo to be rendered correctly in template. Appreciate if this can be addressed.

**Comment by tomasbjerre** [comment]
I'm thinking there can be a new variable `{{urlParts}}` so that you can do:

```hbs
urlParts.0: {{urlParts.0}}
urlParts.1: {{urlParts.1}}
urlParts.2: {{urlParts.2}}
```

That should resovle to:

```
urlParts.0: testchangelog
urlParts.1: bbbbb
urlParts.2: aaaaa
```

**Comment by tomasbjerre** [comment]
releasing this in the maven plugin. open issue again if not working.
