### ISSUE TITLE
Allow `.`(dot) in scope for conventional commits

### ISSUE THREAD

**Issue by mattdibi** [tomasbjerre/git-changelog-lib#132]
As per [Conventional Commit specification](https://github.com/conventional-commits/parser#the-grammar) the `scope` can support:

```
 <scope>           ::= <any UTF8-octets except newline or parens>+
```

[Right now it seems like it doesn't support](https://github.com/tomasbjerre/git-changelog-lib/blob/a5af640c1d3f47c79759483bd8262121f476459f/src/main/java/se/bjurr/gitchangelog/internal/semantic/ConventionalCommitParser.java#L17) the `.` character inside the `scope`.
In my repo I have the following:

```
$ git log
commit 90f58d15182023a72ead841523e8b3c1a8004f15 (HEAD -> master)
Author: Mattia Dal Ben <matthewdibi@gmail.com>
Date:   Fri Apr 29 08:22:35 2022 +0200

    feat(readme.root): add test string
```

If I run `git-changelog-command-line-1.100.1.jar` with:

```
java -jar git-changelog-command-line-1.100.1.jar \
    -fc "f8f7a49b0363fb150281541f9ba9c86e5310c0b6" \
    -tc "90f58d15182023a72ead841523e8b3c1a8004f15" \
    -std -t template/template.hbs -hhf helper.hbs
```

Where `template.hbs` is:

```
Changelog:
{{#commits}}
  * {{firstLetters hash number='10'}} - {{{commitDescription .}}} ({{authorName}})
{{/commits}}
```

I obtain:

```
Changelog:
  * 90f58d1518 -  (Mattia Dal Ben)
```

**Comment by mattdibi** [comment]
Thanks for accepting my contribution and for this awesome project :)

**Comment by tomasbjerre** [comment]
Thanks for contributing!
