### ISSUE TITLE
Does this work with shallow clones?

### ISSUE THREAD

**Issue by Noshire** [tomasbjerre/git-changelog-lib#137]
I hope this is the right platform to ask a question - I saw you do have a question tag (though I can't assign it).

So far, we've parsed the git history for our changelog manually, using `git log` from the current HEAD and doing some postprocessing on the result (omitting "Merge branch" commits etc).

We found that this workflow breaks since we changed the repositories on our CI system to use **shallow cloning**, since commits in the shallow clone don't know their whole ancestry anymore.

Before we do a deep dive and install and configure this plugin, I just wanted to ask whether it will work with shallow cloned repositories. Thanks!

**Comment by tomasbjerre** [comment]
It will work but will only include the commits that have been downloaded. Sounds like you will have same problem you already have with git log.
