### ISSUE TITLE
Any way to embed the current date?

### ISSUE THREAD

**Issue by webminster** [tomasbjerre/git-changelog-lib#138]
Sorry if I'm missing this, but is there a way to get the current date into the changelog? See how to get the commit and other dates, but I'd like to put the date the changelog was generated into the file heading.
-Alan

**Comment by webminster** [comment]
I guess I can use extended variables for this, like -ex "{'var1': \"`date`\"}"

Is there a better way?  Thanks.

**Comment by tomasbjerre** [comment]
I think that would be the best way, yes.
