### ISSUE TITLE
findSemanticVersion method parses only first patch char

### ISSUE THREAD

**Issue by romanlytovchenko** [tomasbjerre/git-changelog-lib#142]
Hello Tomas,
it's really great tool, but using tag with long patch in version (like 1.2.333) works strange for me - it treats the version as 1.2.3.

I've investigate a little and find out regular expression here:
https://github.com/tomasbjerre/git-changelog-lib/blob/a22a611bda640b75fdda014b63c19354b15f7a2f/src/main/java/se/bjurr/gitchangelog/internal/semantic/SemanticVersioning.java#L92

My assumption what is wrong:
 - current result (marked with bold)
printf '1.2.33333' | grep -E '[0-9]+\.[0-9]+\.?[0-9]+?'
**1.2.3**3333
 - my expected result
printf '1.2.33333' | grep -E '[0-9]+\.[0-9]+\.?[0-9]+'
**1.2.33333**

Also I've tested it with older lib version 
`npm i git-changelog-command-line@1.101.1`
and get "long patch"

I hope for a quick fix if my findings are correct

**Comment by tomasbjerre** [comment]
Thanks for reporting! Should be fixed now. Open issue again if not working.
