### ISSUE TITLE
CONVENTIONAL_PATTERN is too restrictive

### ISSUE THREAD

**Issue by alexist** [tomasbjerre/git-changelog-lib#143]
Hi,

In our projects, some issue are committed with this pattern
`feat(JIRA-1234) : Sample commit message`

But the CONVENTIONAL_PATTERN regexp doesn't allow space before `:`
```
private static final Pattern CONVENTIONAL_PATTERN =
      Pattern.compile("^(\\w+)(\\(([\\w\\-\\.:]+)\\)?)?(\\!?):(.+)");
```

It would be nice if this regexp handle space :
```
private static final Pattern CONVENTIONAL_PATTERN =
      Pattern.compile("^(\\w+)(\\(([\\w\\-\\.:]+)\\)?)?(\\!?)[\\s]*?:(.+)");
```

**Comment by tomasbjerre** [comment]
Merged your PR.
