### ISSUE TITLE
Need to check the commits inside of directory 

### ISSUE THREAD

**Issue by Aviral464** [tomasbjerre/git-changelog-lib#145]
I have selected the bitbucket specific branch to build and after the build looking for getting the commits logs in Jenkins by using git changelog plugin and selected "choose 'from' repo" First commit in repo and in section of "Choose 'to' reference" provided branch or tag with the bitbucket branch below in "To reference".

For branch I am able to get the commit logs but need to check commits inside of the particular directory and also for the separate file.

Is that possible to check the commits of the particular directory file by using "Use a subdirectory relative to the workspace" and "Use a configuration file in workspace" option and if possible then please mention the steps and what are the feature of those two please mention that too.

**Comment by tomasbjerre** [comment]
No, not possible

**Comment by Aviral464** [comment]
and how specific commit feature works for getting the commit logs between two dates commits as I have tried by providing commit ID but not getting logs

**Comment by Aviral464** [comment]
and how specific commit feature works for getting the commit logs between two commits as I have tried by providing commit ID but not getting logs?
