### ISSUE TITLE
Question : Create ChangeLog from last tag to previous tags

### ISSUE THREAD

**Issue by skauss** [tomasbjerre/git-changelog-lib#146]
Hi 
I use git-changelog Version 3.27 inside an Jenkins 2.3.88
Right now I get the change log of all commit. (Inside an extra Jenkins job which didn't do the checkout)

Is there a way to get the change log between the last 2 tags ?
We have Tags like 4.12.5 , 4.12.4 ...

I trying with the params Choose 'from' reference and Choose 'to' reference
but I don't know what to insert in "From/To reference"
Regards
Stephan

**Comment by tomasbjerre** [comment]
Yes, you can do it with the command line tool like this:

```sh
npx git-changelog-command-line -std --from-ref 4.12.4 --to-ref 4.12.5
```

Or with the jenkins-plugin:

```sh
 def changelogString = gitChangelog returnType: 'STRING',
  from: [type: 'REF', value: '4.12.4'],
  to: [type: 'REF', value: '4.12.5']

  println changelogString
```

**Comment by tomasbjerre** [comment]
Something like this maby: https://stackoverflow.com/questions/36547680/how-do-i-get-the-output-of-a-shell-command-executed-using-into-a-variable-from-j
