### ISSUE TITLE
Feature request: Support for importing built-in helpers from handlerbars.java

### ISSUE THREAD

**Issue by vjda** [tomasbjerre/git-changelog-lib#148]
It would be great to have a way to import automatically the built-in helpers from the dependency [handlebars.java](https://github.com/jknack/handlebars.java#built-in-helpers) in order to reuse them in the templates to render the changelog text.

Currently, if we try to use one of the helpers available in handlebars.java we get an exception. For instance, for a template similar to this:

```hbs
{{#commits}}
    {{#ifCommitBreaking .}}
- **{{capitalizeFirst messageTitle}}** ([{{hash}}]({{gitLabProjectUrl}}/commit/{{hashFull}}))
    {{/ifCommitBreaking}}
{{/commits}}
```

`git-changelog-command-line` throws the following error:

```
Exception in thread "main" com.github.jknack.handlebars.HandlebarsException: inline@64a82ec9:16:6: could not find helper: 'capitalizeFirst'
- **{{capitalizeFirst messageTitle}}** ([{{hash}}]({{gitLabProjectUrl}}/commit/{{hashFull}}))
      ^
```

Notice that `capitalizeFirst` comes from [`StringHelpers.java`](https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java).

I've been diving into the `git-changelog-lib` code for some time but I'm not very familiar with it, so I can't really estimate how much effort it would take to do the functionality. But let me know if I can help at all.

Thanks in advance.

**Comment by tomasbjerre** [comment]
StringHelpers is now included.

**Comment by vjda** [comment]
awesome! thanks @tomasbjerre !
