### ISSUE TITLE
{{ownerName}}/{{repoName}} empty if git remote origin is not set

### ISSUE THREAD

**Issue by edeso** [tomasbjerre/git-changelog-lib#149]
shouldn't this raise an error instead of silently ignoring it?

thanks!

**Comment by tomasbjerre** [comment]
Sounds reasonable. But I also don't want complicated code to get this behavior, not worth it.

**Comment by edeso** [comment]
no problem. was just surprised that i ended up with empty values when it worked on another box. maybe documenting the need for **origin** when using `{{ownerName}}`, `{{repoName}}` can be documented?

couldn't find a list of default placeholders just now. is there one?

**Comment by tomasbjerre** [comment]
The context is here:
https://github.com/tomasbjerre/git-changelog-lib#context

**Comment by edeso** [comment]
i see. well then let me suggest

https://github.com/tomasbjerre/git-changelog-lib/pull/150

**Comment by edeso** [comment]
pleasure. thank you :)
