### ISSUE TITLE
Tests fail when executed from a forked repository 

### ISSUE THREAD

**Issue by reda-alaoui** [tomasbjerre/git-changelog-lib#157]
You can reproduce on https://github.com/Cosium/git-changelog-lib .

Makes it hard to contribute :cry:

**Comment by tomasbjerre** [comment]
But it works if you clone the main repository? I mean you can just add you fork as a remote and push your feature branch there before opening a PR.

**Comment by tomasbjerre** [comment]
Yes I agree. Im not very proud of the test cases in the project, they do protect from regression but it is not very clear what they test.

**Comment by tomasbjerre** [comment]
I added a clearer failure message when this happens. Closing this issue with that fix and hope it helps.
