### ISSUE TITLE
Unexcepted exception in GitInit

### ISSUE THREAD

**Issue by rodorico83** [tomasbjerre/git-changelog-lib#17]
I’m getting an exception at 
 
git-changelog-lib/src/main/java/se/bjurr/gitchangelog/internal/git/GitRepo.java
``` 
 Did not find a GIT repo in /var/jenkins/workspace/EBP-Build-Test
java.lang.RuntimeException: Did not find a GIT repo in /var/jenkins/workspace/EBP-Build-Test
	at se.bjurr.gitchangelog.internal.git.GitRepo.<init>(GitRepo.java:69)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:306)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:320)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:107)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:27)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```
The path is correct, corresponds to the workspace path and the .git folder is present, so I was wondering why this exception is popping up. Any idea ?
 
Jenkins version : 1.6.50
Plugin version: 1.7
Git client plugin 1.19.5
Git plugin 2.4.2
System Debian. 
 
 

``` 
public GitRepo(File repo) {
	  try {
	   File repoFile = new File(repo.getAbsolutePath());
	   File gitRepoFile = new File(repo.getAbsolutePath() + "/.git");
	   if (gitRepoFile.exists()) {
	    repoFile = gitRepoFile;
	   }
	   FileRepositoryBuilder builder = new FileRepositoryBuilder()//
	     .findGitDir(repoFile)//
	     .readEnvironment();
	   if (builder.getGitDir() == null) {
	    throw new RuntimeException("Did not find a GIT repo in " + repo.getAbsolutePath());
	   }
	   this.repository = builder.build();
	  } catch (IOException e) {
	   throw propagate(e);
	  }
	}
```

Any Idea ??

**Comment by tomasbjerre** [comment]
Do you use Jenkins GIT plugin? Or do you have a "free style" job with a custom build script where you do something like "git clone ..."?

The second one will likely give this problem.

**Comment by tomasbjerre** [comment]
Maby a quick fix is to clone like this:
`git clone git@github.com:user/my-project.git .`
So that the git repo ends up in the root of the workspace, where the plugin expects it to be.

**Comment by rodorico83** [comment]
I'm using the Git plugin for checkout, is set to do a clean every time before but not a clone.

**Comment by tomasbjerre** [comment]
Ok, should be very easy to fix. I'll have a look later today.

**Comment by rodorico83** [comment]
i can post my job configuration if you want

**Comment by tomasbjerre** [comment]
Thanks but its not needed =)

**Comment by tomasbjerre** [comment]
I may actually need the configuration =) Can you post it?

**Comment by tomasbjerre** [comment]
You can also try the command line tool on that folder, see if that also fails:
https://github.com/tomasbjerre/git-changelog-command-line

**Comment by rodorico83** [comment]
Hi tomas, Here is my configuration
![capture1](https://cloud.githubusercontent.com/assets/6552843/13669019/e61447ca-e6c0-11e5-82aa-2799514ce463.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6552843/13669021/e8645236-e6c0-11e5-8662-1d949fcf034c.PNG)
![capture3](https://cloud.githubusercontent.com/assets/6552843/13669023/eaeabe5a-e6c0-11e5-8ea3-00389fc768bb.PNG)

**Comment by rodorico83** [comment]
I've test several configurations of changelog, what I want is to use as from and to references two branches which are available via string build parameters.

**Comment by tomasbjerre** [comment]
Did you try the command line tool?
https://github.com/tomasbjerre/git-changelog-command-line
And if you cd to `/var/jenkins/workspace/EBP-Build-Test` you can do `git status`? Just to make sure its a working git repo.

**Comment by rodorico83** [comment]
I did not tried the command tool, but git is working properly on the Jenkins workspace, git status ,checkout ... no problem at all.

**Comment by rodorico83** [comment]
I will try with the command tool

**Comment by rodorico83** [comment]
After copy the changelog command line folder in the workspace and run it, it outputs the changelog.

git status as build command before the git changelog post-build step runs also fine.

**Comment by rodorico83** [comment]
more test shows that is running fine in the master node, but when I execute in the slave exception pop-ups but when I use the command line in the slave also works, I have to say that the java installed in the slave is not via package as is an old system and java 1.7 is not available.

**Comment by rodorico83** [comment]
Hi Tomas, same problem with the new release

**Comment by rodorico83** [comment]
here the log of the build with only git status command and the error just after 
```
Started by remote host 10.40.17.160
Building remotely on ebpdvlp-abuild (EBP-BUILD) in workspace /var/jenkins/workspace/EBP-Build-Test
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url ssh://git@ebphq-git2.siemens.ebp.railb.be:7999/EBP/ebp-main.git # timeout=10
Pruning obsolete local branches
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching upstream changes from ssh://git@ebphq-git2.siemens.ebp.railb.be:7999/EBP/ebp-main.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress ssh://git@ebphq-git2.siemens.ebp.railb.be:7999/EBP/ebp-main.git +refs/heads/*:refs/remotes/origin/* --prune
 > git rev-parse refs/remotes/origin/feature/CM-59-create-a-plan-for-integration2^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/refs/heads/feature/CM-59-create-a-plan-for-integration2^{commit} # timeout=10
Checking out Revision 34976a84a11f85fef45dce21eafc4ea3ed98127d (refs/remotes/origin/feature/CM-59-create-a-plan-for-integration2)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 34976a84a11f85fef45dce21eafc4ea3ed98127d # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D refs/heads/feature/CM-59-create-a-plan-for-integration2 # timeout=10
 > git checkout -b refs/heads/feature/CM-59-create-a-plan-for-integration2 34976a84a11f85fef45dce21eafc4ea3ed98127d
 > git rev-list 34976a84a11f85fef45dce21eafc4ea3ed98127d # timeout=10
Notified Stash for commit with id 34976a84a11f85fef45dce21eafc4ea3ed98127d
[EBP-Build-Test] $ /bin/bash -xe /tmp/hudson754788027607713994.sh
+ git status
On branch refs/heads/feature/CM-59-create-a-plan-for-integration2
nothing to commit, working directory clean
---
--- Git Changelog ---
---
Did not find a GIT repo in /var/jenkins/workspace/EBP-Build-Test
Notified Stash for commit with id 34976a84a11f85fef45dce21eafc4ea3ed98127d
Finished: SUCCESS
```

**Comment by rodorico83** [comment]
Using the normal git changelog post-build action also works fine.

**Comment by tomasbjerre** [comment]
I'll make a new attempt later today then =)

**Comment by tomasbjerre** [comment]
Try 1.9 =) Should work now. Works for me with slaves setup.

**Comment by rodorico83** [comment]
Hi Tomas i've tried 1.10 and it works like a charm, what was the issue ? it was executing on master ?

**Comment by tomasbjerre** [comment]
Nice =)

Yes, it was executed on master. This was the fix:
https://github.com/jenkinsci/git-changelog-plugin/commit/d7a5fc7b0af73ea3eb041af8500d6646a473b54c

**Comment by rodorico83** [comment]
ok thanks for the fix !!
