### ISSUE TITLE
Calling `getNextSemanticVersion()` influences `getHighestSemanticVersion()`

### ISSUE THREAD

**Issue by sschuberth** [tomasbjerre/git-changelog-lib#170]
When calling `getNextSemanticVersion()` before `getHighestSemanticVersion()` (on the same `GitChangelogApi` instance), that influences the result of `getHighestSemanticVersion()`.

In my test case, calling `getHighestSemanticVersion()` alone would result in "1.0.1", but if `getNextSemanticVersion()` is called before (which yields "1.1.0"), then `getHighestSemanticVersion()` suddenly returns "0.0.0".

Is this intended?

**Comment by tomasbjerre** [comment]
Sounds really strange, will have a look later.

**Comment by sschuberth** [comment]
I believe this happens because of

https://github.com/tomasbjerre/git-changelog-lib/blob/d33434ce19c9b8aaf78760358a73e9ed8cbf66e9/src/main/java/se/bjurr/gitchangelog/api/GitChangelogApi.java#L192

which alters the state of the current `GitChangelogApi`.

**Comment by tomasbjerre** [comment]
Releasing a fix for this in 1.173.1. Open issue again if not working.
