### ISSUE TITLE
Changelog only for the last tag?

### ISSUE THREAD

**Issue by Edivad99** [tomasbjerre/git-changelog-lib#171]
Is there a way to generate the changelog for just the last tag?

**Comment by tomasbjerre** [comment]
If you are about to make a new release you can use this tool to get the highest tag in the repo. And generate a changelog between that and head.

If the release is made and the tag exist. You want a changelog only between 2 existing tags. You can add an if-statement in the handlebars template when looping tags, and only render stuff for that tag.

Probably easiest to fiddle with it using the command line tool, there are examples in readme https://github.com/tomasbjerre/git-changelog-command-line

**Comment by Edivad99** [comment]
Is this possible using the git-changelog-gradle-plugin plugin?

**Comment by tomasbjerre** [comment]
Probably yes. Depends on your exact scenario.
