### ISSUE TITLE
Version of Jackson 2.5.x has Security Vulnerabilities

### ISSUE THREAD

**Issue by kingargyle** [tomasbjerre/git-changelog-lib#181]
When trying to bring this in to our repository internally, the code scanning software flagged this as having potential security vulnerabilities due to dependencies.

In particular the version of Jackson being used.

https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-32111

**Comment by tomasbjerre** [comment]
I forgot about this issue. It was solved a while back and is now using `2.15.2`.
