### ISSUE TITLE
[feature-request] Simulate the next commit

### ISSUE THREAD

**Issue by toxn** [tomasbjerre/git-changelog-lib#187]
add 3 arguments to the `gitChangelog` and `gitChanglogSemanticVersion` tasks:
- `--message`: Simulate the next commit with that message (obviously with an empty sha).
- `--message-file`: Simulate the next commit with the message being in that file (useful as a `commit-msg` git hook).
- `--tag`: Additionally to `--message*`, simulate a tagged commit, would conveniently replace the sha as a valid ref.

Those would permit to build an almost valid changelog **before** committing, thus integrating an up-to-date changelog in eich commit. It should warn or fail if `prependToFile` is `true`.

**Comment by tomasbjerre** [comment]
Moving this issue from the Gradle plugin to the library.

**Comment by tomasbjerre** [comment]
There is a special tag called `Unreleased`, it is filtered out in the default template:
https://github.com/tomasbjerre/git-changelog-lib/blob/2c6c9c70c1ab82abb427a7f6dcbdc4dd3c3d2d20/src/main/resources/changelog.mustache#L6

Perhaps you can do the opposite and include the commits in that tag.

**Comment by toxn** [comment]
This doesn't cover my intended use case, where I use the plugin as a commit-hook to update the changelog after the commit message has been written, but before the commit is created.

**Comment by toxn** [comment]
Currently, whenever I tag, which is when I really want the changelog to be up-to-date, I must 
- commit
- tag the commit
- generate the changelog
- remove the tag
- commit --amend
- recreate the tag
- push

My intention was to do all that in one go with a commit-hook

**Comment by tomasbjerre** [comment]
Sounds like you can do that if you have your own template. Copy the default template and remove the `{{#ifEquals name "Unreleased"}}`.

**Comment by tomasbjerre** [comment]
This GitHub action does this:
https://github.com/marketplace/actions/git-changelog-github-release

With this template:
https://github.com/tomasbjerre/git-changelog-github-release/blob/0cb4399c4010741bba743dc4f4c63bad9f22cbbe/action.yml#L19
