### ISSUE TITLE
using jenkins variables in mustache templates.

### ISSUE THREAD

**Issue by techlunacy** [tomasbjerre/git-changelog-lib#22]
Is it possible to use standard jenkins variables in the mustashe templates.

such as JOB_NAME?
or any of the other ones referenced here:
https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables

thanks.

**Comment by tomasbjerre** [comment]
I think they will work if you configure the template inline in Jenkins. But if not, I think it should be implemented.

**Comment by techlunacy** [comment]
i have added this to my build.
`<h1> Version: {{JOB_NAME}} </h1>`
`<h1> Version: ${JOB_NAME} </h1>`
i will see what happens over night.

**Comment by techlunacy** [comment]
this is the version that worked for me.
`<h1> Version: ${JOB_NAME} </h1>`
will test with other variables but i will assume they will work
thanks.
