### ISSUE TITLE
changelog is generating incorrect order of commits/Issues

### ISSUE THREAD

**Issue by joychugh** [tomasbjerre/git-changelog-lib#23]
Here is the scenario:
in Develop I add commit a
Create Release Branch v1.0 
add commit b in release Branch
add commit c in Develop Branch (for v1.2)
add commit d in release Brach
Finish Release tag with v.10
merge to master & develop

When I generate the gitChangelog in develop branch
it puts commit b,c,d in v1.0 Whereas commit c has not yet released.

When I do a release 1.2 ( which has commit c and no other commit) 
it doesn't even show up in the changlog

The only way commit `c` can be seen in correct place is if i do 
`fromRef=1.0`
`toRef=1.2`
i will see `c` listed under 1.2. Not otherwise

```
task gitChangelogTask(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    filePath = "CHANGELOG.md";
    templateContent = new File('changelog.mustache').getText('UTF-8');
    customIssues = [
            [ "Added", "(?i)(added)\\s*(?i)(JIRA-\\d{1,6})(.*)", "https://mycompanyjira.com/browse/\${PATTERN_GROUP_2}", "\${PATTERN_GROUP_3}"],
            [ "Fixed", "(?i)(fixed)\\s*(?i)(JIRA-\\d{1,6})(.*)", "https://mycompanyjira.com/browse/\${PATTERN_GROUP_2}", "\${PATTERN_GROUP_3}"],
    ]
    jiraIssuePattern = '(?!)' // to skip jira issues for now.
    untaggedName = "Next Release";
    ignoreCommitsWithoutIssue = true;
}
```

**Comment by joychugh** [comment]
The bug seems to be here
https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/main/java/se/bjurr/gitchangelog/internal/git/GitRepo.java#L101

If there are commits in order like

commit a
tag 1.0
commit b
commit c (not in tag 1.0)

It will go through `a` add it to the commits for the `untagged` tag
set currentTagName to 1.0
and then add b and c 
where as c is not part of the tag 1.0

I looked around and found this 
https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/ListTags.java

or if you can add commits by 
sort tags
get a list of commits between each tag 
and then add them it should produce a good result. the starting can be from
HEAD to latest_tag .. and so on 
what do you think?

**Comment by tomasbjerre** [comment]
I will look at this later today. Can you also supply content of your `changelog.mustache`?

**Comment by tomasbjerre** [comment]
```
* a (tag2)
* b (tag1)
* c
```
I suspcect `git.log().add(tag2).call()` returns a, b and c.
I suspcect `git.log().addRange(tag1, tag2).call()` returns b and a (reverse order).

Should be an easy fix, expect a release later today.

**Comment by tomasbjerre** [comment]
Is this what your repo looks like?
```
* c (dev, tag:1.2)
|   * d (rel, tag: 1.0)
|   * b
| /
* a
```

**Comment by joychugh** [comment]
* Merge rel back to master & dev
|  \
|  (rel, tag: 1.2)
| /
* c 
|   * d (rel, tag: 1.0)
|   * b
| /
* a

**Comment by tomasbjerre** [comment]
Not sure I understand exactly what your repo looks like. What is the output of this?
```
git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
```

Looks like you create tags in the release-branch, not after merging it to master.

I am use to tagging master and I believe that is the correct way of doing it in [GIT Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

Sorry, this was a bit more complex then I thought earlier today =)

**Comment by joychugh** [comment]
Let me try to run some tests with the gitflow of making tags on master and ill get back to you with results,

**Comment by joychugh** [comment]
jchugh:changelog jchugh$ git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
    *       6102f44 2016-04-07 (HEAD -> develop)  Merge branch 'release/1.0' into develop (Joy Chugh)
    |\  
    * |     f9e20c4 2016-04-07  ADDED DATASVC-1234 Commit C in DEV (Joy Chugh)
    | | *           d83168f 2016-04-07 (tag: 1.0, master)  Merge branch 'release/1.0' (Joy Chugh)
    | | |\  
    | | |/  
    | |/|   
    | * |   115f0d7 2016-04-07  Fixed DATASVC-1234 Commit D in 1.0 (Joy Chugh)
    | * |   aa3733e 2016-04-07  ADDED DATASVC-1234 Commit B in REL 1.0 (Joy Chugh)
    |/ /  
    * |     5061917 2016-04-07  ADDED DATASVC-1234 Commit A (Joy Chugh)
    |/  
    *       80e3d57 2016-04-07  ADDED DATASVC-1234 initial commit (Joy Chugh)

**Comment by joychugh** [comment]
After I do the above and use the following settings
```
task gitChangelogTask(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    filePath = "CHANGELOG.md";
    templateContent = new File('changelog.mustache').getText('UTF-8');
    customIssues = [
            [ "Added", "(?i)(added)\\s*(?i)(DATASVC-\\d{1,6})(.*)", "https://jira.ops.aol.com/browse/\${PATTERN_GROUP_2}", "\${PATTERN_GROUP_3}"],
            [ "Fixed", "(?i)(fixed)\\s*(?i)(DATASVC-\\d{1,6})(.*)", "https://jira.ops.aol.com/browse/\${PATTERN_GROUP_2}", "\${PATTERN_GROUP_3}"],
    ]
    jiraIssuePattern = '(?!)'
    untaggedName = "Next Release";
    ignoreCommitsWithoutIssue = true;
    toRef='develop'
}
```

Using the following template 
```
{{#tags}}
## {{name}}
{{#issueTypes}}
### {{name}}
 {{#issues}}
  {{#hasIssue}}
   {{#hasLink}}
* [{{title}}]({{link}})
   {{/hasLink}}
   {{^hasLink}}
* {{title}}
   {{/hasLink}}
  {{/hasIssue}}
  {{^hasIssue}}
  {{/hasIssue}}
 {{/issues}}
{{/issueTypes}}
{{/tags}}

```
I run the task on develop branch i get this 
```

## Next Release
### Added
* [ Commit A](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ Commit B in REL 1.0](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ Commit C in DEV](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ initial commit](https://jira.ops.aol.com/browse/DATASVC-1234)
### Fixed
* [ Commit D in 1.0](https://jira.ops.aol.com/browse/DATASVC-1234)

```

Running On Master 

```
## 1.0
### Added
* [ Commit A](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ Commit B in REL 1.0](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ initial commit](https://jira.ops.aol.com/browse/DATASVC-1234)
### Fixed
* [ Commit D in 1.0](https://jira.ops.aol.com/browse/DATASVC-1234)
```

**Comment by joychugh** [comment]
```
jchugh:changelog jchugh$ git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
*       7037f3e 2016-04-07 (HEAD -> master, tag: 1.1)  Merge branch 'release/1.1' (Joy Chugh)
|\  
| *     7f301be 2016-04-07 (develop)  Fixed DATASVC-1234 Commit E in DEV (Joy Chugh)
| *     6102f44 2016-04-07  Merge branch 'release/1.0' into develop (Joy Chugh)
| |\  
| * |   f9e20c4 2016-04-07  ADDED DATASVC-1234 Commit C in DEV (Joy Chugh)
* | |           d83168f 2016-04-07 (tag: 1.0)  Merge branch 'release/1.0' (Joy Chugh)
|\ \ \  
| | |/  
| |/|   
| * |   115f0d7 2016-04-07  Fixed DATASVC-1234 Commit D in 1.0 (Joy Chugh)
| * |   aa3733e 2016-04-07  ADDED DATASVC-1234 Commit B in REL 1.0 (Joy Chugh)
| |/  
| *     5061917 2016-04-07  ADDED DATASVC-1234 Commit A (Joy Chugh)
|/  
*       80e3d57 2016-04-07  ADDED DATASVC-1234 initial commit (Joy Chugh)
```

Running on master 

```
## 1.1
### Fixed
* [ Commit E in DEV](https://jira.ops.aol.com/browse/DATASVC-1234)
## 1.0
### Added
* [ Commit A](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ Commit B in REL 1.0](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ Commit C in DEV](https://jira.ops.aol.com/browse/DATASVC-1234)
* [ initial commit](https://jira.ops.aol.com/browse/DATASVC-1234)
### Fixed
* [ Commit D in 1.0](https://jira.ops.aol.com/browse/DATASVC-1234)
```

Setting

```
task gitChangelogTask(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    filePath = "CHANGELOG.md";
    templateContent = new File('changelog.mustache').getText('UTF-8');
    customIssues = [
            [ "Added", "(?i)(added)\\s*(?i)(DATASVC-\\d{1,6})(.*)", "https://jira.ops.aol.com/browse/\${PATTERN_GROUP_2}", "\${PATTERN_GROUP_3}"],
            [ "Fixed", "(?i)(fixed)\\s*(?i)(DATASVC-\\d{1,6})(.*)", "https://jira.ops.aol.com/browse/\${PATTERN_GROUP_2}", "\${PATTERN_GROUP_3}"],
    ]
    jiraIssuePattern = '(?!)'
    untaggedName = "Next Release";
    ignoreCommitsWithoutIssue = true;
}
```

As you can see Commit C should be in 1.1 not 1.0 since it was done on the develop branch after the release 1.0 was branched from it. (B and D were done on 1.0 as you can see from previous example)

**Comment by joychugh** [comment]
Since you already have code which does toRef and fromRef 
if you get do gitTags b/w each tag falling between the fromRef and toRef and then flatten all those List<Tag> lists, it should give you a better output since if i do fromRef 1.0 to 1.1 it gives me a perfect changelog 
```

## 1.1
### Added
* [ Commit C in DEV](https://jira.ops.aol.com/browse/DATASVC-1234)
### Fixed
* [ Commit E in DEV](https://jira.ops.aol.com/browse/DATASVC-1234)


```

**Comment by tomasbjerre** [comment]
Perhaps it is that easy =) The tags would have to be sorted first, by the commit time of the commits they refer to...
I added a [test case](https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/test/java/se/bjurr/gitchangelog/internal/git/GitRepoTest.java#L94) for now, will look at this as soon as I find the time.

**Comment by joychugh** [comment]
I think if you sort it by time it can give the same issue since that is what is causing the issue in the first place. if people tag using some fixed convention you can sort them lexicographically and then do the diff b/w each one starting from the bottom since usually people tag using a certain convention. If they don't then they can't use the plugin. It should solve the issue for most of the people who follow conventions.

**Comment by tomasbjerre** [comment]
I may have a fix ready in PR #25. Only problem I can see is that it is about 10 times slower then before.

**Comment by tomasbjerre** [comment]
I made a release with this fix.

**Comment by tomasbjerre** [comment]
Open issue again if not fixed =)

**Comment by joychugh** [comment]
Thanks! I did not have time to test it yet, when do you plan to release this version to gradle plugins repository I would like to use it at my work

**Comment by tomasbjerre** [comment]
Its already there: https://plugins.gradle.org/plugin/se.bjurr.gitchangelog.git-changelog-gradle-plugin
