### ISSUE TITLE
Missing Pull Request Merges in Git Changelog

### ISSUE THREAD

**Issue by emoshaya-cognito** [tomasbjerre/git-changelog-lib#27]
The "Git Changelog" Publish Action works great in listing commits in the Jenkins Build Summary. However, it fails to list any of the Pull Request merges. Please see screenshots below of Actual Github Commits and the Jenkins Summary Page missing all the PR merges.

![github_commits](https://cloud.githubusercontent.com/assets/8818542/15010286/1ee81098-11e3-11e6-9873-6092a1f9d1cc.png)

![jenkins_changelog](https://cloud.githubusercontent.com/assets/8818542/15010291/244eb5be-11e3-11e6-9d9f-2e977e0aaea4.png)

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/git-changelog-plugin/issues/3
