### ISSUE TITLE
Getting full hash from Commit object

### ISSUE THREAD

**Issue by flasher297** [tomasbjerre/git-changelog-lib#30]
Now length of hash is limited to 15 digits.
`private static String toHash(String input) {
  return input.substring(0, 15);
 }`
It would be hady to have ability to get full hash in addition to shortened or to have ability to change length of available hash.

For example for integration with git in TFS I need to have full hash value to have proper link to commit in TFS in changelog.

**Comment by tomasbjerre** [comment]
I added `{{hashFull}}` to solve this. Open issue again if any problems!

**Comment by flasher297** [comment]
Thanks for so fast response! This is fine.
Will be waiting for the next release.

**Comment by tomasbjerre** [comment]
It is released.

Den 9 aug. 2016 12:29 skrev "Alex" <notifications@github.com>:
