### ISSUE TITLE
Auto hash link not configurable

### ISSUE THREAD

**Issue by Thadir** [tomasbjerre/git-changelog-lib#34]
At the moment the generated documentation work quite nice. However it tries to create links on the commit hahes. And it does not derive it or is configurable (at least clearly).

For example it generates a commit based on the has as folows:
`https://github.com/tomasbjerre/git-changelog-lib/commit/6f8c1fb96a908b1`

But in my case it should be:
`https://bitbucket.org/{owner of repo}/{name of repo}/commits/`.

This could be dynamecly derived from the git url thats given:
git@bitbucket.org:{owner of repo}/{name of repo}.git (and yeah the commits part I guess should be configurable seeing github and bitbucket have a difrent method there.)

**Comment by tomasbjerre** [comment]
This is part of your template. You have this in your template right?

[{{hash}}](https://github.com/tomasbjerre/git-changelog-lib/commit/{{hash}}) {{authorName}} *{{commitTime}}*

**Comment by Thadir** [comment]
Totaly richt used the default template without looking.

There was also a question, is there a way to make a header of a merge, and a sub of all the commits that are part of it>

**Comment by tomasbjerre** [comment]
No there is currently no way to do that :(
