### ISSUE TITLE
Git Change log show only Merges or have Merge as its own Tag

### ISSUE THREAD

**Issue by Thadir** [tomasbjerre/git-changelog-lib#35]
I was hoping that it would be able to only show Merges to Master like you can do with the folowing git log command:

git log --dense --merges --simplify-merges --pretty=oneline --date-order --date=iso8601 {#tag}..HEAD

The merge summarises what the branch your merging back in to your master branch, makin the change log a lot denser and readable and quicker to use as a sort of in this release we had this changes.

Maybe even better is to just show the {merge} tag, that you can use then as a header and with sub tags for the commits as it is now.

**Comment by tomasbjerre** [comment]
Adding a boolean to each commit, like isMerge, should be very easy to implement. Then you can loop all commits and only print a header if its a merge.

**Comment by tomasbjerre** [comment]
The `merge` boolean attribute on commits is now released in the lib + plugins. Use it like this: https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/test/resources/templates/testMerges.mustache

**Comment by Thadir** [comment]
Ill test it tomrow on our test systems. Thanks.

**Comment by mschilli87** [comment]
I found this issue looking for a way to exclude merges from the commit range of my changelog and found the link above to be dead. It looks like the file was moved here: https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/test/resources/mix/testMerges.mustache
