### ISSUE TITLE
Annotated tags support

### ISSUE THREAD

**Issue by etienne-me** [tomasbjerre/git-changelog-lib#36]
Is that possible to include the description and/or releases notes (using Gitlab) for annotated tags ?

**Comment by tomasbjerre** [comment]
Perhaps you can use the maven or gradle plugins, if that is what you use for building your application.
Or the command line tool should also work for you.

All mentioned in the readme.

**Comment by etienne-me** [comment]
I actually use the Jenkins plugin, following your example it would be something like 

```
`* tags
 - name
 - message
 * commits
  - authorName
  - authorEmailAddress
  - commitTime
...
```

To be clear, I would like to include in my changelog file what we get with  
```
git tag -n
```
Is that something which needs to be implemented ?

Thanks for your reply and sorry for the inconvenience.

**Comment by tomasbjerre** [comment]
Getting the annotation of annotated tags like that is not supported. So yes, it needs to be implemented. Found this thread that might help to do so: http://stackoverflow.com/questions/14913829/get-all-tags-of-a-repository-with-jgit

**Comment by tomasbjerre** [comment]
This is now released. Open issue again if any problems!

**Comment by etienne-me** [comment]
Thank you for your work, it works great !
