### ISSUE TITLE
Displaying multiple tags per commit

### ISSUE THREAD

**Issue by ernsheong** [tomasbjerre/git-changelog-lib#37]
Are we able to display multiple tags at the same commit? Right now it looks like if a commit has two tags, one of them is not displayed.

Version 1.32

**Comment by tomasbjerre** [comment]
No I did not include that use case.

**Comment by ernsheong** [comment]
OK thanks. No worries.

**Comment by tomasbjerre** [comment]
You may want to ignore one of them. There is an option to ignore tags by regexp.
