### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by carloscaverobarca** [tomasbjerre/git-changelog-lib#42]
It would be nice to integrate changelog with GitLab. The APIs and OAuth are not compatible with GitHub: 
- In GitHub the issue number is "number". In [GitLab](https://docs.gitlab.com/ce/api/issues.html) is "iid".
- In GitHub the link to the issue is "html_url". In GitLab is "web_url".
- The OAuth in GitHub is "Authorization: token <TOKEN>". In [GitLab](https://docs.gitlab.com/ee/api/README.html#personal-access-tokens) is "PRIVATE_TOKEN <TOKEN>".

I can send a PR if needed.

**Comment by tomasbjerre** [comment]
You are using the command-line tool right? Its released now.

**Comment by carloscaverobarca** [comment]
Yes I am using the command line! Great! I wanted to also use it in the jenkins plugin. Is it possible?

**Comment by tomasbjerre** [comment]
Yes i'll probably have time for that tomorrow.

Den 25 mars 2017 21:49 skrev "Carlos Cavero" <notifications@github.com>:

**Comment by tomasbjerre** [comment]
I just released it in Jenkins now. Should be in the update sites within a few hours. Open issue again if not working.

**Comment by carloscaverobarca** [comment]
Nice! Thanks!
