### ISSUE TITLE
Add mustache example how to link to github issue

### ISSUE THREAD

**Issue by k3b** [tomasbjerre/git-changelog-lib#45]
This is github issue #45 at github..com/tomasbjerre/git-changelog-lib/issues/45

When i add a commit message "#45: some commit text" then commit is linked to the issue:

Is it possible to use this in an a generated changelog? 

the example https://github.com/tomasbjerre/git-changelog-lib/blob/master/changelog.mustache seems to be hardcoded-linked to Jira issues.

I would like to link to github-issues instead.

Here is an example where commit-messages are linked to issues: https://github.com/k3b/APhotoManager/issues/21

**Comment by tomasbjerre** [comment]
Depends on how you use this lib. 
Here is an example with the Maven plugin:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/git-changelog-maven-plugin-example/pom.xml#L118

It uses this template:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/git-changelog-maven-plugin-example/changelog.mustache

Will create:
https://github.com/tomasbjerre/git-changelog-maven-plugin/blob/master/git-changelog-maven-plugin-example/CHANGELOG.md

Or with Gradle:
https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/git-changelog-gradle-plugin-example/build.gradle#L84

**Comment by k3b** [comment]
thanks. the example was exactly what i was looking for. So i need a [github oauth-token](https://help.github.com/articles/git-automation-with-oauth-tokens/) and the generation is not over the local git clone but over the github-web-api
