### ISSUE TITLE
Ability to grab the url from the git config.

### ISSUE THREAD

**Issue by dmodoomsirius** [tomasbjerre/git-changelog-lib#49]
hello
I was wondering if its possible or if its already implemented to get the URL form the git config so i can easily have it useable across multiple repos. either through copy and paste or in a script that is applied. 

thank you for your time.

**Comment by tomasbjerre** [comment]
Which URL do you need?

Den 22 juli 2017 06:58 skrev "Dmodoom Sirius" <notifications@github.com>:

**Comment by dmodoomsirius** [comment]
https://github.com/BuiltBrokenModding/SBM-ObsidianBucket/ is the url i need so i can do https://github.com/BuiltBrokenModding/ICBM-Classic/blob/development/build.gradle#L111

**Comment by tomasbjerre** [comment]
I added `ownerName` and `repoName` variables. See: https://github.com/tomasbjerre/git-changelog-lib/blob/master/changelog.mustache

What do you think?

**Comment by tomasbjerre** [comment]
I'm releasing this now.

**Comment by dmodoomsirius** [comment]
Awesome thank you very much!

**Comment by dmodoomsirius** [comment]
just found a bug https://github.com/VoltzEngine-Project/Build is the url its supposed to use and its using https://github.com/com/VoltzEngine-Project/commit/ I am thinking its doing that because it is a org.

**Comment by tomasbjerre** [comment]
Perhaps you have a clone url that does not end with ".git"? But still, it is a bug if that does not work!

Here is the clone URL I tested with: https://github.com/tomasbjerre/git-changelog-lib/blob/master/src/test/java/se/bjurr/gitchangelog/internal/git/GitRepoDataTest.java#L19

**Comment by dmodoomsirius** [comment]
I do not use the url that ends with .git i use 
```
[remote "origin"]
	url = https://github.com/VoltzEngine-Project/Build
	fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by tomasbjerre** [comment]
I'm releasing a fix now!

**Comment by dmodoomsirius** [comment]
Thank you very much for the quick Fix!
