### ISSUE TITLE
Jenkins Changelog Plugin: Gets changes from master branch only

### ISSUE THREAD

**Issue by esramirez** [tomasbjerre/git-changelog-lib#50]
I am looking to get the changes from develop branch.  I have specified the plugin to use develop branch but doesnt seem to obey it.

My environment:
Jenkins version 2.32.3
git version 2.8.2.windows.1

Jenkins changelog configuration:
![image](https://user-images.githubusercontent.com/12220617/28529779-683415d6-705f-11e7-87ef-f1458a026e87.png)

Jenkins GIT configuration:
![image](https://user-images.githubusercontent.com/12220617/28529862-b476b9c6-705f-11e7-892e-9dff392146fe.png)

**Comment by tomasbjerre** [comment]
the "chose to reference" drop down menu needs to be changed to *A branch or tag (Enter below)*

**Comment by esramirez** [comment]
Thank you @tomasbjerre  for speedy reply. After changing the configuration as suggested I am getting the changelog for the targeted branch.
