### ISSUE TITLE
How to filter a message body item?

### ISSUE THREAD

**Issue by FOhis** [tomasbjerre/git-changelog-lib#53]
Hello,
how can i filter a message body item?

e.g. from message

--- 8< --- 8< begin message --- 8< --- 8< 
titel

detailed information

(cherry picked from commit ....

# Conflicts:
#	export.cpp

--- 8< --- 8< end message --- 8< --- 8< 

remove the following lines
1) (cherry picked from commit ...
2) a line start with comment char # 

could you please provide a method ignoreMessageBodyItemsIfItemMatches similary to method ignoreCommitsIfMessageMatches?
I would like to create 2 changelogs
1) for internal use with information about cherry pick and git comments e.g. conflict infos
2) for external use without information about cherry pick and git comments

Therefore, I can not globally disable git commit info (cherry picked from ... and comments in commit messages.

I use git-changelog-lib with git-changelog-command-line Tool.

Thank you very much
FO

**Comment by tomasbjerre** [comment]
It now has helpers. See readme.

**Comment by FOhis** [comment]
Thank you very much
FO
