### ISSUE TITLE
git log showing a commit bit plugin saying commit not found. 

### ISSUE THREAD

**Issue by dmodoomsirius** [tomasbjerre/git-changelog-lib#73]
https://github.com/DarkGuardsman/JsonContentBuilderLib is the repo i am trying to create a changelog on. 

log https://gist.github.com/dmodoomsirius/14d748635d7bc1fae70b67e090f0fe9c

**Comment by tomasbjerre** [comment]
Looks like you are giving `fromRef` a commit and not a reference (branch or
tag).

Den fre 17 maj 2019 kl 00:58 skrev Dmodoom Sirius <notifications@github.com

**Comment by dmodoomsirius** [comment]
Did something change? That used to work. If it did how can I reference a commit for it to generate a change log from a commit to head?

**Comment by tomasbjerre** [comment]
Use fromCommit
https://github.com/tomasbjerre/git-changelog-gradle-plugin/blob/master/git-changelog-gradle-plugin-example/build.gradle#L188

**Comment by dmodoomsirius** [comment]
Thank you very much!
