### ISSUE TITLE
Git Reverts

### ISSUE THREAD

**Issue by caruano95** [tomasbjerre/git-changelog-lib#76]
When using [git revert](https://git-scm.com/docs/git-revert) a new commit is created to undo a particular change, with the commit message "Revert xxxx". It's often used to undo merging a feature branch.
Currently, if an issue is removed from the main branch with a revert, it would still appear in the Changelog because the other commits (For example, the merge commit) is still there.

Is there any way to prevent this from happening ? 
Something like "Exclude an issue if a commit with the issue id and the word 'Revert' is in the git log"

**Comment by tomasbjerre** [comment]
No I cannot think of a way to do that without a change in this library.

Den tis 20 aug. 2019 20:27caruano95 <notifications@github.com> skrev:
