### ISSUE TITLE
Is there a way to use this plugin in a Jenkins Scripted Pipline ?

### ISSUE THREAD

**Issue by shimi25** [tomasbjerre/git-changelog-lib#80]
Hello , 

I'm using Jenkins for Windows C++ and .Net project that make use of series of Cmake commands.
The Build is comprised of several git repositories which i clone from our GitLab using google repo utility. 

Is there a way for the plugin to work in a Scripted Pipeline ? 
Also there is a way to run this utility as command line i a Windows Env ? 

Thanks 

Shimon.

**Comment by tomasbjerre** [comment]
This software can be used:
 * With a [Gradle plugin](https://github.com/tomasbjerre/git-changelog-gradle-plugin).
 * With a [Maven plugin](https://github.com/tomasbjerre/git-changelog-maven-plugin).
 * With a [Jenkins plugin](https://github.com/jenkinsci/git-changelog-plugin).
 * With a [Bitbucket Server plugin](https://github.com/tomasbjerre/git-changelog-bitbucket-plugin).
 * From [command line](https://github.com/tomasbjerre/git-changelog-command-line).
 * As a library [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22git-changelog-lib%22).
