### ISSUE TITLE
Could you please provide any commit message filtration example.

### ISSUE THREAD

**Issue by pooja1889** [tomasbjerre/git-changelog-lib#82]
I am using git changelog plugin in my project to generate release notes. I have requirement to filter commit message based on feat,bugfix and refactor. 
But I  am not able to find any example. Does this plugin support commit message filtration.

Also I have more requirement to get summary of jira story. I am using useJira feature of git changelog. But not able to get title of jira story. Here is my code snippet
def changelogString = gitChangelog returnType: 'CONTEXT',
        from: [type: 'REF', value:latestTag],
        to: [type: 'REF', value:'HEAD'],
        ignoreCommitsIfMessageMatches: '^Merge.',
        ignoreCommitsWithoutIssue: 'true', 
       jira:[issuePattern: 'CICD-*', password: '', server: '', username: '']
        template: """
# Changelog

Changelog for {{ownerName}} {{repoName}}.

{{#tags}}
## {{name}}
 {{#issues}}
  {{#hasIssue}}
   {{#hasLink}}
### {{name}} [{{issue}}]({{link}}) {{title}} {{#hasIssueType}} *{{issueType}}* {{/hasIssueType}} {{#hasLabels}} {{#labels}} *{{.}}* {{/labels}} {{/hasLabels}}
   {{/hasLink}}
   {{^hasLink}}
### {{name}} {{issue}} {{title}} {{#hasIssueType}} *{{issueType}}* {{/hasIssueType}} {{#hasLabels}} {{#labels}} *{{.}}* {{/labels}} {{/hasLabels}}
   {{/hasLink}}
  {{/hasIssue}}
  {{^hasIssue}}
### {{name}}
  {{/hasIssue}}

  {{#commits}}
**{{{messageTitle}}}**

{{#messageBodyItems}}
 * {{.}} 
{{/messageBodyItems}}

[{{hash}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}} *{{commitTime}}*

  {{/commits}}

 {{/issues}}
{{/tags}}
---
"""
Set<String> issueIdentifiers = new TreeSet<>()
 changelogString.issues.each {issue ->
 println(issue.name)
 println(issue.issue)
 println(issue.title)
}

changelogString.issues.each {hasIssue ->
 println(hasIssue.title)
}
changelogString.issues.each {hasLink ->
 println(hasLink.link)
}
changelogString.issues.each {hasDescription ->
 println(hasDescription.description)
}

When I am using returnType String, It failed but in CONTEXT it doesn't print title
I have supply valid credentials of Jira

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/git-changelog-plugin/issues/45
