### ISSUE TITLE
How to filter git commit message title

### ISSUE THREAD

**Issue by pooja1889** [tomasbjerre/git-changelog-lib#84]
I didn't find any example to filter out the commit message based on feature and bug fix.
As far as I know it supports only ignorecommitmessage

Does is it possible to filter the message based on pattern. if yes then please provide example

https://github.com/jenkinsci/git-changelog-plugin/issues/45

**Comment by tomasbjerre** [comment]
You can ignore commits based on its commit message with:
```
ignoreCommitsIfMessageMatches: 'regular expression here',
```

**Comment by pooja1889** [comment]
But it will ignore the message. I want to contain message which have string like feat bug and rest can be ignore

**Comment by tomasbjerre** [comment]
https://stackoverflow.com/questions/1240275/how-to-negate-specific-word-in-regex

**Comment by pooja1889** [comment]
Is there any way to remove duplicate commit message also

**Comment by pooja1889** [comment]
In my use case I have to generate release notes bases on last tag and HEAD  whenever code goes in to production.
So Is there any way we can append the git changelog output on top of previously created  release notes

**Comment by tomasbjerre** [comment]
If using the jenkins plugin, you can do that with Groovy.

**Comment by tomasbjerre** [comment]
It now has helpers. See readme.
