### ISSUE TITLE
Want to fetch jira issue summary

### ISSUE THREAD

**Issue by 2018201920201920** [tomasbjerre/git-changelog-lib#89]
Please provde a clear description of your issue.

If you do not provide any information that can be investigated, expect this issue to be closed without action.
I am using Git Changelog3.0 plugin for release notes publishing.But I am not able to fetch  Jira issue summary & jira labels  by using {{issue.summary}} ,

Please help

**Comment by tomasbjerre** [comment]
Open issue in that plugin. This is the library.

**Comment by 2018201920201920** [comment]
What is   
{{ description }} here??
