### ISSUE TITLE
Add support for Changelog context pre-processing.

### ISSUE THREAD

**Issue by jeacott1** [tomasbjerre/git-changelog-lib#92]
It would be very helpful if this project provided an extension mechanism where context pre-processors could take the existing final Changelog context and pass it through a list of processors (Visitors perhaps?) that could freely manipulate the context before the final render.

With this addition it would be relatively easy to add support for "Conventional Commits" formatted messages for example or other content pre-processing requirements.

**Comment by tomasbjerre** [comment]
What is the use case?

You can get the context:
https://github.com/tomasbjerre/git-changelog-lib/blob/8596ffa8173a4c537140c21860530e967965f69c/src/main/java/se/bjurr/gitchangelog/api/GitChangelogApi.java#L74

**Comment by jeacott1** [comment]
I can get the context, but I cant modify it without rebuilding the software.
I'd like to be able to dynamically drop in some script or a plugin jar - perhaps groovy or whatever.
I want to be able to modify the changelog context  (even if its just the extensions map), so that I can process the changelog and effectively create a new set of context entries from the existing.
Imagine that I want to support Conventional Commits for example, and I'd like to be able to arbitrarily reformat the body text, or issue text from the 'original' changelog context. I cant see how to do this currently. 
I've been trying with a customIssues something like this (some documentation on this feature would be helpful):
```
 "customIssues": [
  { "name": "Fixes", "pattern": "fixes"},
  { "name": "Bugs", "pattern": "bug" },
  { "name": "Features", "pattern": "feature" },
  { "name": "Uncategorised", "pattern": "^((?!bug|fixes|feature).)*$" }
 ]
```

and whilst this does get me some of the way there, I can't get output as pretty or sensible as I'd like. The customIssues list doesn't seem to be processed in order so if an item has an entry containing both fixes and feature for example, I cant specify a priority.

With a provision for processing the context before render() I could do with it whatever I want.

**Comment by tomasbjerre** [comment]
@jeacott1 I started fiddling with this. Implemented some features in this lib to support it. I am utilising the helpers feature in the rendering library (Handlebars) to do adjustments before rendering model.

This is what I have right now, but there is a bit more work to do. Hopefully it is possible to support conventional commits like this.

```
# git clone https://gitlab.com/html-validate/html-validate.git
# cd html-validate

highestTag=$(npx git-changelog-command-line \
 --major-version-pattern "^[Bb]reaking.*" \
 --minor-version-pattern "^[Ff]eat.*" \
 --print-highest-version-tag)

echo Last release detected as $highestTag

nextVersion=$(npx git-changelog-command-line \
 --major-version-pattern "^[Bb]reaking.*" \
 --minor-version-pattern "^[Ff]eat.*" \
 --print-next-version)

echo Next release based on commits is: $nextVersion

echo Changelog would be prepended with:

npx git-changelog-command-line \
 --from-ref $highestTag \
 --to-ref HEAD \
 --stdout \
 --template-content "

{{#hasType commits type='feat'}}
### Features
  {{#commits}}
    {{#isType messageTitle type='feat'}}
      {{printCommit .}}
    {{/isType}}
  {{/commits}}

{{/hasType}}

{{#hasType commits type='fix'}}
### Bug Fixes
  {{#commits}}
    {{#isType messageTitle type='fix'}}
{{printCommit .}}
    {{/isType}}
  {{/commits}}

{{/hasType}}


{{#hasType commits type='chore'}}
### Chores
  {{#commits}}
    {{#isType messageTitle type='chore'}}
{{printCommit .}}
    {{/isType}}
  {{/commits}}

{{/hasType}}

" \
--register-handlebars-helper "
Handlebars.registerHelper('hasType', function(commits, options) {
  const commitType = options.hash['type']
  for (let i = 0; i < commits.length; i++) {
    if (new RegExp('^' + commitType + '.*').test(commits[i].message)) {
      return options.fn(this);
    }
  }
  return options.inverse(this);
});

Handlebars.registerHelper('isType', function(messageTitle, options) {
  const commitType = options.hash['type']
  if (new RegExp('^' + commitType + '.*').test(messageTitle)) {
    return options.fn(this);
  } else {
      return options.inverse(this);
  }
});

Handlebars.registerHelper('printCommit', function(commit, options) {
  const message = commit.messageTitle.split(':')[1].trim()
  return ' - ' + message + ' ([' + commit.hash + '](https://gitlab.com/html-validate/html-validate/commit/' + commit.hashFull + '))';
});
"

```

**Comment by tomasbjerre** [comment]
Released in all tools now.
