### ISSUE TITLE
Lack of logging

### ISSUE THREAD

**Issue by peter-daplyn-mortgagegym-com** [tomasbjerre/git-changelog-lib#98]
I'm trying to connect to our Jira Cloud from the Jenkins plugin and can't get it working whatever I try.

If there was some logging (optionally) that gave some feedback as to what was happening, there's a possibility I may be able to work out the problem myself.

Thanks!

**Comment by tomasbjerre** [comment]
I would need more specific details of what happens.

**Comment by peter-daplyn-mortgagegym-com** [comment]
Hi Tomas - that's what I was thinking as well, hence the request for additional logging.
It seems to parse and find the issue ids, but there's details from jira & no indication that it's trying to connect to jira.

**Comment by tomasbjerre** [comment]
Open issue in the plugin. Follow issue template. Supply the information you are currently getting.

**Comment by peter-daplyn-mortgagegym-com** [comment]
ok - will provide more details when I get round to trying it again.
